// <auto-generated />
using System;
using KanbanDemandas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KanbanDemandas.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KanbanDbContext))]
    [Migration("20260928052928_CamposBloqueadosEtapa")]
    partial class CamposBloqueadosEtapa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KanbanDemandas.Core.Entities.AcaoAutomacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("ParametrosJson")
                        .HasColumnType("longtext");

                    b.Property<int>("RegraAutomacaoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegraAutomacaoId");

                    b.ToTable("AcoesAutomacao", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.AlertaCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RegraAutomacaoId")
                        .HasColumnType("int");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ResolvidoPorId")
                        .HasColumnType("int");

                    b.Property<int>("Severidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegraAutomacaoId");

                    b.HasIndex("CartaoId", "Resolvido");

                    b.ToTable("AlertasCartao", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<bool>("Comprimido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<int>("EnviadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArmazenado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("TamanhoArmazenadoBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.HasIndex("EnviadoPorId");

                    b.ToTable("Anexos", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("CartaoPaiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Estimativa")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<int>("ListaId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<bool>("OrigemPortal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int?>("SistemaId")
                        .HasColumnType("int");

                    b.Property<int?>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoSolicitacao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoPaiId");

                    b.HasIndex("ListaId");

                    b.HasIndex("SistemaId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Cartoes", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.CartaoDesenvolvedor", b =>
                {
                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CartaoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CartaoDesenvolvedores", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.CartaoEtiqueta", b =>
                {
                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("int");

                    b.HasKey("CartaoId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("CartaoEtiquetas", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int?>("CartaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Editado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemTarefaId")
                        .HasColumnType("int");

                    b.Property<bool>("Publico")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CartaoId");

                    b.HasIndex("ItemTarefaId");

                    b.ToTable("Comentarios", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.DefinicaoCampo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("DefineDataInicioCartao")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<int>("ListaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OpcoesSelecao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<bool>("PedirNovamenteACadaEntrada")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Preenchimento")
                        .HasColumnType("int");

                    b.Property<int>("RegraReentrada")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListaId");

                    b.ToTable("DefinicoesCampo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            DefineDataInicioCartao = false,
                            Excluido = false,
                            ListaId = 5,
                            Nome = "Data Homologado",
                            Obrigatorio = true,
                            Ordem = 1,
                            PedirNovamenteACadaEntrada = true,
                            Preenchimento = 0,
                            RegraReentrada = 0,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            DefineDataInicioCartao = false,
                            Excluido = false,
                            ListaId = 5,
                            Nome = "Homologado Por",
                            Obrigatorio = false,
                            Ordem = 2,
                            PedirNovamenteACadaEntrada = false,
                            Preenchimento = 0,
                            RegraReentrada = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            DefineDataInicioCartao = false,
                            Excluido = false,
                            ListaId = 6,
                            Nome = "Data Prevista de Change",
                            Obrigatorio = true,
                            Ordem = 1,
                            PedirNovamenteACadaEntrada = false,
                            Preenchimento = 0,
                            RegraReentrada = 0,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 4,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            DefineDataInicioCartao = false,
                            Excluido = false,
                            ListaId = 6,
                            Nome = "Número do Change",
                            Obrigatorio = false,
                            Ordem = 2,
                            PedirNovamenteACadaEntrada = false,
                            Preenchimento = 0,
                            RegraReentrada = 0,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.EmailCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<string>("Cc")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CorpoHtml")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Enviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EnviadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("ErroEnvio")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Para")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.HasIndex("EnviadoPorId");

                    b.ToTable("EmailsCartao", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("#607D8B");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("QuadroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuadroId");

                    b.ToTable("Etiquetas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#E53935",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Excluido = false,
                            Nome = "Bug",
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#43A047",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Excluido = false,
                            Nome = "Feature",
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#1E88E5",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Excluido = false,
                            Nome = "Melhoria",
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#FB8C00",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Excluido = false,
                            Nome = "Urgente",
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cor = "#8E24AA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Excluido = false,
                            Nome = "Técnico",
                            QuadroId = 1
                        });
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.EventoAutomacaoPendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Campo")
                        .HasColumnType("int");

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExecutarEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Gatilho")
                        .HasColumnType("int");

                    b.Property<int?>("ListaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAlvoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.HasIndex("ExecutarEm");

                    b.ToTable("EventosAutomacaoPendentes", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ExecucaoAutomacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartaoId")
                        .HasColumnType("int");

                    b.Property<string>("ChaveDisparo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DesfazerJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DesfeitaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DesfeitaPorId")
                        .HasColumnType("int");

                    b.Property<int>("EmailsEnviados")
                        .HasColumnType("int");

                    b.Property<string>("Erro")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Gatilho")
                        .HasColumnType("int");

                    b.Property<int>("MensagensTeams")
                        .HasColumnType("int");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuadroId")
                        .HasColumnType("int");

                    b.Property<int>("RegraAutomacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.HasIndex("QuadroId", "OcorridoEm");

                    b.HasIndex("RegraAutomacaoId", "CartaoId", "ChaveDisparo");

                    b.ToTable("ExecucoesAutomacao", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Feriado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("RecorrenteAnual")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.ToTable("Feriados", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.HistoricoAtividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlterouDataInicio")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataInicioAnterior")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Estornado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ListaDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("ListaOrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ValorNovo")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ListaOrigemId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("CartaoId", "OcorridoEm");

                    b.HasIndex("ListaDestinoId", "OcorridoEm");

                    b.ToTable("HistoricoAtividades", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ItemTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<int?>("CartaoPromovidoId")
                        .HasColumnType("int");

                    b.Property<bool>("Concluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int?>("DesenvolvedorId")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.HasIndex("CartaoPromovidoId");

                    b.HasIndex("DesenvolvedorId");

                    b.ToTable("ItensTarefa", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("BloquearEntradaComPendencias")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CamposFixosBloqueados")
                        .HasColumnType("int");

                    b.Property<int>("CamposFixosExigidos")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("EhBacklog")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("LimiteWip")
                        .HasColumnType("int");

                    b.Property<int?>("ListaPaiId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int?>("OrdemFluxo")
                        .HasColumnType("int");

                    b.Property<int>("QuadroId")
                        .HasColumnType("int");

                    b.Property<string>("StatusPortal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ListaPaiId");

                    b.HasIndex("QuadroId");

                    b.ToTable("Listas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloquearEntradaComPendencias = false,
                            CamposFixosBloqueados = 0,
                            CamposFixosExigidos = 0,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            EhBacklog = true,
                            Excluido = false,
                            Nome = "Backlog",
                            Ordem = 1,
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 2,
                            BloquearEntradaComPendencias = false,
                            CamposFixosBloqueados = 0,
                            CamposFixosExigidos = 0,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            EhBacklog = false,
                            Excluido = false,
                            LimiteWip = 10,
                            Nome = "A Fazer",
                            Ordem = 2,
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 3,
                            BloquearEntradaComPendencias = false,
                            CamposFixosBloqueados = 0,
                            CamposFixosExigidos = 0,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            EhBacklog = false,
                            Excluido = false,
                            LimiteWip = 5,
                            Nome = "Em Andamento",
                            Ordem = 3,
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 4,
                            BloquearEntradaComPendencias = false,
                            CamposFixosBloqueados = 0,
                            CamposFixosExigidos = 0,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            EhBacklog = false,
                            Excluido = false,
                            LimiteWip = 3,
                            Nome = "Code Review",
                            Ordem = 4,
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 5,
                            BloquearEntradaComPendencias = false,
                            CamposFixosBloqueados = 0,
                            CamposFixosExigidos = 0,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            EhBacklog = false,
                            Excluido = false,
                            Nome = "Homologação",
                            Ordem = 5,
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 6,
                            BloquearEntradaComPendencias = false,
                            CamposFixosBloqueados = 0,
                            CamposFixosExigidos = 0,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            EhBacklog = false,
                            Excluido = false,
                            Nome = "Pré-produção",
                            Ordem = 6,
                            QuadroId = 1
                        },
                        new
                        {
                            Id = 7,
                            BloquearEntradaComPendencias = false,
                            CamposFixosBloqueados = 0,
                            CamposFixosExigidos = 0,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            EhBacklog = false,
                            Excluido = false,
                            Nome = "Concluído",
                            Ordem = 7,
                            QuadroId = 1
                        });
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("CartaoOrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Lida")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LidaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaoOrigemId");

                    b.HasIndex("DestinatarioId", "Lida");

                    b.ToTable("Notificacoes", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ParametroSistema", b =>
                {
                    b.Property<string>("Chave")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Chave");

                    b.ToTable("ParametrosSistema", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Quadro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("#1565C0");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("TemplateQuadroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Quadros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#1565C0",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Descricao = "Quadro principal do time",
                            Excluido = false,
                            Nome = "Time de Desenvolvimento"
                        });
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.RegraAutomacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CondicoesJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("ExigirTodasCondicoes")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Gatilho")
                        .HasColumnType("int");

                    b.Property<int?>("ListaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ParametrosGatilhoJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("QuadroId")
                        .HasColumnType("int");

                    b.Property<bool>("SomenteHorarioComercial")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UltimaExecucaoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ListaId");

                    b.HasIndex("QuadroId", "Gatilho");

                    b.ToTable("RegrasAutomacao", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.RelacaoCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<int>("CartaoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("CartaoOrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaoDestinoId");

                    b.HasIndex("CartaoOrigemId");

                    b.ToTable("RelacoesCartao", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Reuniao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Ata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int?>("CartaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemTarefaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CartaoId");

                    b.HasIndex("ItemTarefaId");

                    b.ToTable("Reunioes", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ReuniaoParticipante", b =>
                {
                    b.Property<int>("ReuniaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReuniaoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ReuniaoParticipantes", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Sistemas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Excluido = false,
                            Nome = "Portal do Cliente"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Excluido = false,
                            Nome = "ERP Interno"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Excluido = false,
                            Nome = "App Mobile"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Excluido = false,
                            Nome = "Integrações"
                        });
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Fechada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Meta")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("QuadroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuadroId");

                    b.ToTable("Sprints", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.SprintCartao", b =>
                {
                    b.Property<int>("SprintId")
                        .HasColumnType("int");

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SprintId", "CartaoId");

                    b.HasIndex("CartaoId");

                    b.ToTable("SprintCartoes", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.SugestaoAutomacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DecididoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DecididoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PropostaJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuadroId")
                        .HasColumnType("int");

                    b.Property<int>("RegraAutomacaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegraAutomacaoId");

                    b.HasIndex("CartaoId", "Status");

                    b.HasIndex("QuadroId", "Status");

                    b.ToTable("SugestoesAutomacao", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.TemplateCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("CamposPadrao")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoPadrao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("ItensTarefaPadrao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("QuadroId")
                        .HasColumnType("int");

                    b.Property<string>("TitulopadraO")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuadroId");

                    b.ToTable("TemplatesCartao", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.TemplateQuadro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EstruturaJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TemplatesQuadro", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("NotificarPorEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReceberEmailsAutomacao")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Email = "admin@empresa.com",
                            Excluido = false,
                            Nome = "Admin",
                            NotificarPorEmail = false,
                            ReceberEmailsAutomacao = true
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Email = "ana.lima@empresa.com",
                            Excluido = false,
                            Nome = "Ana Lima",
                            NotificarPorEmail = true,
                            ReceberEmailsAutomacao = true
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Email = "bruno.costa@empresa.com",
                            Excluido = false,
                            Nome = "Bruno Costa",
                            NotificarPorEmail = true,
                            ReceberEmailsAutomacao = true
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Email = "carla.mendes@empresa.com",
                            Excluido = false,
                            Nome = "Carla Mendes",
                            NotificarPorEmail = false,
                            ReceberEmailsAutomacao = true
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPorId = 1,
                            Email = "diego.santos@empresa.com",
                            Excluido = false,
                            Nome = "Diego Santos",
                            NotificarPorEmail = true,
                            ReceberEmailsAutomacao = true
                        });
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ValorCampoCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<bool>("CriadoAutomaticamente")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPreenchimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DefinicaoCampoId")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("HistoricoOrigemId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroEntradaNaLista")
                        .HasColumnType("int");

                    b.Property<int>("PreenchidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ValorAnteriorAutomatico")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DefinicaoCampoId");

                    b.HasIndex("HistoricoOrigemId");

                    b.HasIndex("PreenchidoPorId");

                    b.HasIndex("CartaoId", "DefinicaoCampoId", "NumeroEntradaNaLista");

                    b.ToTable("ValoresCampoCartao", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.VinculoGit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Autor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("CartaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Repositorio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId", "Tipo", "Repositorio", "Identificador")
                        .IsUnique();

                    b.ToTable("VinculosGit", (string)null);
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.AcaoAutomacao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.RegraAutomacao", "RegraAutomacao")
                        .WithMany("Acoes")
                        .HasForeignKey("RegraAutomacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegraAutomacao");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.AlertaCartao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("Alertas")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.RegraAutomacao", "RegraAutomacao")
                        .WithMany()
                        .HasForeignKey("RegraAutomacaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cartao");

                    b.Navigation("RegraAutomacao");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Anexo", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("Anexos")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("EnviadoPor");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Cartao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "CartaoPai")
                        .WithMany("CartosFilhos")
                        .HasForeignKey("CartaoPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KanbanDemandas.Core.Entities.Lista", "Lista")
                        .WithMany("Cartoes")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Sistema", "Sistema")
                        .WithMany("Cartoes")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CartaoPai");

                    b.Navigation("Lista");

                    b.Navigation("Sistema");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.CartaoDesenvolvedor", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("Desenvolvedores")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "Usuario")
                        .WithMany("CartoesDesenvolvedor")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.CartaoEtiqueta", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("Etiquetas")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Etiqueta", "Etiqueta")
                        .WithMany("CartaoEtiquetas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Comentario", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("Comentarios")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KanbanDemandas.Core.Entities.ItemTarefa", "ItemTarefa")
                        .WithMany("Comentarios")
                        .HasForeignKey("ItemTarefaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Autor");

                    b.Navigation("Cartao");

                    b.Navigation("ItemTarefa");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.DefinicaoCampo", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Lista", "Lista")
                        .WithMany("DefinicoesCampo")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.EmailCartao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("Emails")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("EnviadoPor");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Etiqueta", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Quadro", "Quadro")
                        .WithMany("Etiquetas")
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quadro");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ExecucaoAutomacao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KanbanDemandas.Core.Entities.RegraAutomacao", "RegraAutomacao")
                        .WithMany()
                        .HasForeignKey("RegraAutomacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("RegraAutomacao");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.HistoricoAtividade", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("Historico")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Lista", "ListaDestino")
                        .WithMany()
                        .HasForeignKey("ListaDestinoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KanbanDemandas.Core.Entities.Lista", "ListaOrigem")
                        .WithMany()
                        .HasForeignKey("ListaOrigemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("ListaDestino");

                    b.Navigation("ListaOrigem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ItemTarefa", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("ItensTarefa")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "CartaoPromovido")
                        .WithMany()
                        .HasForeignKey("CartaoPromovidoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "Desenvolvedor")
                        .WithMany()
                        .HasForeignKey("DesenvolvedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cartao");

                    b.Navigation("CartaoPromovido");

                    b.Navigation("Desenvolvedor");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Lista", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Lista", "ListaPai")
                        .WithMany("Sublistas")
                        .HasForeignKey("ListaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KanbanDemandas.Core.Entities.Quadro", "Quadro")
                        .WithMany("Listas")
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaPai");

                    b.Navigation("Quadro");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Notificacao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "CartaoOrigem")
                        .WithMany()
                        .HasForeignKey("CartaoOrigemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "Destinatario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoOrigem");

                    b.Navigation("Destinatario");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.RegraAutomacao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Lista", "Lista")
                        .WithMany("RegrasAutomacao")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KanbanDemandas.Core.Entities.Quadro", "Quadro")
                        .WithMany()
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lista");

                    b.Navigation("Quadro");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.RelacaoCartao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "CartaoDestino")
                        .WithMany("RelacoesDestino")
                        .HasForeignKey("CartaoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "CartaoOrigem")
                        .WithMany("RelacoesOrigem")
                        .HasForeignKey("CartaoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CartaoDestino");

                    b.Navigation("CartaoOrigem");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Reuniao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("Reunioes")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KanbanDemandas.Core.Entities.ItemTarefa", "ItemTarefa")
                        .WithMany("Reunioes")
                        .HasForeignKey("ItemTarefaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Autor");

                    b.Navigation("Cartao");

                    b.Navigation("ItemTarefa");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ReuniaoParticipante", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Reuniao", "Reuniao")
                        .WithMany("Participantes")
                        .HasForeignKey("ReuniaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reuniao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Sprint", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Quadro", "Quadro")
                        .WithMany("Sprints")
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quadro");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.SprintCartao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("Sprints")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.Sprint", "Sprint")
                        .WithMany("Cartoes")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.SugestaoAutomacao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.RegraAutomacao", "RegraAutomacao")
                        .WithMany()
                        .HasForeignKey("RegraAutomacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("RegraAutomacao");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.TemplateCartao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Quadro", "Quadro")
                        .WithMany("TemplatesCartao")
                        .HasForeignKey("QuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quadro");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ValorCampoCartao", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("ValoresCampo")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.DefinicaoCampo", "DefinicaoCampo")
                        .WithMany("Valores")
                        .HasForeignKey("DefinicaoCampoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanbanDemandas.Core.Entities.HistoricoAtividade", "HistoricoOrigem")
                        .WithMany()
                        .HasForeignKey("HistoricoOrigemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KanbanDemandas.Core.Entities.Usuario", "PreenchidoPor")
                        .WithMany()
                        .HasForeignKey("PreenchidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("DefinicaoCampo");

                    b.Navigation("HistoricoOrigem");

                    b.Navigation("PreenchidoPor");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.VinculoGit", b =>
                {
                    b.HasOne("KanbanDemandas.Core.Entities.Cartao", "Cartao")
                        .WithMany("VinculosGit")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Cartao", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Anexos");

                    b.Navigation("CartosFilhos");

                    b.Navigation("Comentarios");

                    b.Navigation("Desenvolvedores");

                    b.Navigation("Emails");

                    b.Navigation("Etiquetas");

                    b.Navigation("Historico");

                    b.Navigation("ItensTarefa");

                    b.Navigation("RelacoesDestino");

                    b.Navigation("RelacoesOrigem");

                    b.Navigation("Reunioes");

                    b.Navigation("Sprints");

                    b.Navigation("ValoresCampo");

                    b.Navigation("VinculosGit");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.DefinicaoCampo", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Etiqueta", b =>
                {
                    b.Navigation("CartaoEtiquetas");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.ItemTarefa", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Reunioes");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Lista", b =>
                {
                    b.Navigation("Cartoes");

                    b.Navigation("DefinicoesCampo");

                    b.Navigation("RegrasAutomacao");

                    b.Navigation("Sublistas");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Quadro", b =>
                {
                    b.Navigation("Etiquetas");

                    b.Navigation("Listas");

                    b.Navigation("Sprints");

                    b.Navigation("TemplatesCartao");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.RegraAutomacao", b =>
                {
                    b.Navigation("Acoes");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Reuniao", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Sistema", b =>
                {
                    b.Navigation("Cartoes");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Sprint", b =>
                {
                    b.Navigation("Cartoes");
                });

            modelBuilder.Entity("KanbanDemandas.Core.Entities.Usuario", b =>
                {
                    b.Navigation("CartoesDesenvolvedor");

                    b.Navigation("Notificacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
